### ISSUE TITLE
Frequent Metroid Prime 2 Crashes

### ISSUE THREAD

**Issue by zachThePerson** [shiiion/dolphin#42]
To be clear, I believe this is a problem with upstream Dolphin as well, but I'm posting it here as I feel PrimeHack is in a unique position to focus more attention on Metroid Prime related fixes.

Basically Prime 1 and 3 work perfectly, but Prime 2 suffers from frequent crashes every 30-60 minutes. Save-states are unable to help, as if you save-state before a crash, the crash will still occur around the same time. For example if I save-state, walk for 3 minutes across a level, then open a door and it crashes, when I load that save state the game will crash again around that same point.

**Comment by SirMangler** [comment]
Without more information this will be hard for us to investigate, but please note, savestates are inherently incredibly unstable, and should absolutely not be used without expectation of them causing crashes, or worsening existing glitches and problems.

The cause may be related to `Dual Core`, which is known to de-stable this game. Try playing the game with that setting disabled and see if it still occurs.

**Comment by zachThePerson** [comment]
I think I already tried based on someone else's recommendation that but I'll try again.

The issue tends to happen most when going through doors and loading in new assets. The game will just freeze and if I remember right will still show high CPU usage. It also makes it difficult to shut down.

I'll try it out later today and give a more detailed report.

**Comment by LuceoX30** [comment]
I seem to be getting a similar issue, myself. But instead, the game doesn't even load. Dolphin just freezes where I'm forced to utilise Task Manager to shut it down. Essentially... MP2 is a no-go.

**Comment by zachThePerson** [comment]
I had the same problem with MP2. Try turning off all action-replay codes. For me it was one of the "Unlock all items," which was causing it to not boot at all

**Comment by LuceoX30** [comment]
The problem was fixed. It's never a good idea to break the game in that far extent without crating a save, first...

**Comment by Wonderfall** [comment]
I've also had a crash within the first hour of gameplay on MP2. But I didn't use savestate and kept going for a few more hours, and it went well - I guess crashes can happen, more often under some conditions and in specific places. Anyway I'll keep monitoring for them if it happens again so we can determine the common issue.

I've been playing MP1 without issues though (more than 10 hours straight!), no crash whatsoever. If it helps I use DX12 as backend, x3 IR, x16 AF, custom textures, and I had to enable the _Synchronise GPU thread_ option (though I can boot without it, I had a glitch the first time without it).

**Comment by SirMangler** [comment]
> Also DX12 (in my case) may be less stable than DX11.

This is the case. D3D11 is older and every GPU (which could run Dolphin) completely supports it, and it has been supported in Dolphin for much longer than D3D12 and Vulkan. It is the best backend for stability.

I have recently heard of a problem in MP2 **GameCube** causing frequent crashes, but this problem is inherent to Dolphin Emulator itself and not us. More information is required to determine the problem. 

@zachThePerson Are you playing on the Trilogy version or GameCube? And are you on PAL or NTSC?

**Comment by zachThePerson** [comment]
I was using NTSC Trilogy version that I ripped myself (tried re-ripping on 2 different Wiis and it didn't fix it, just to rule that out)

**Comment by Wonderfall** [comment]
By any chance, did you try switching backend as discussed earlier and toggling _Synchronise GPU thread_?

I've played 20 hours of MP2 and got 2-3 crashes, this is on DX12 on a GTX 1070. I didn't mind the few crashes, especially since the performance was great (I even play on a 4k monitor at x6 IR right now!).

You should also verify your ISO integrity (Dolphin -> Righ-click on the game -> Properties -> Verify).

> The issue tends to happen most when going through doors and loading in new assets.

Seems to be related to shaders compilation. Maybe some related settings could help with that.

**Comment by zachThePerson** [comment]
It's been awhile since I first posted and a haven't played since, but I'm about 90% sure I did try different backends. I'm finishing up a large work project atm, but I'll try some different backends come monday

**Comment by zachThePerson** [comment]
Ok, I loaded up primehack and DX12 was already selected. I've already tried Synchronize GPU on/off and that either didn't help or caused more issues. I don't know why this is MP2 only, as I don't think I've had a single crash with the other 2 games

**Comment by zachThePerson** [comment]
Ok, so I loaded up Primehack and DX12 was loaded, which means I was getting my crashes on that backend. I loaded up DX11 and while it didn't completely lock up, there were some serious 5-20 second freezes during the alpha splinter fight. Managed to get to Agon Wastes without a crash though, so progress maybe. Still curious why this happens only with Echoes and not the other two though

**Comment by Wonderfall** [comment]
You could also try OpenGL, if you have an Nvidia GPU, and see if that improves the freezes (otherwise turn down some graphics options). But yeah I get it, I've played 20 hours of MP1, 5+hours of MP3, and both never crashed - unlike MP2 which did a few times. Emulation things I guess. :)

**Comment by SirMangler** [comment]
This is an existing problem with Dolphin Master related to bugs in the graphics and shader code, an area we are not familiar with. Currently this is a problem outside the scope of the project. This issue has been closed for inactivity, if there is new and specific information on how this problem can be tackled, it can be included into a new issue.
